import { Book } from '@/types';

export const BOOKS: Book[] = [
  { id: 1,  name: 'Genesis',          abbrev: 'Gen',  testament: 'OT' },
  { id: 2,  name: 'Exodus',           abbrev: 'Exo',  testament: 'OT' },
  { id: 3,  name: 'Leviticus',        abbrev: 'Lev',  testament: 'OT' },
  { id: 4,  name: 'Numbers',          abbrev: 'Num',  testament: 'OT' },
  { id: 5,  name: 'Deuteronomy',      abbrev: 'Deu',  testament: 'OT' },
  { id: 6,  name: 'Joshua',           abbrev: 'Jos',  testament: 'OT' },
  { id: 7,  name: 'Judges',           abbrev: 'Jdg',  testament: 'OT' },
  { id: 8,  name: 'Ruth',             abbrev: 'Rut',  testament: 'OT' },
  { id: 9,  name: '1 Samuel',         abbrev: '1Sa',  testament: 'OT' },
  { id: 10, name: '2 Samuel',         abbrev: '2Sa',  testament: 'OT' },
  { id: 11, name: '1 Kings',          abbrev: '1Ki',  testament: 'OT' },
  { id: 12, name: '2 Kings',          abbrev: '2Ki',  testament: 'OT' },
  { id: 13, name: '1 Chronicles',     abbrev: '1Ch',  testament: 'OT' },
  { id: 14, name: '2 Chronicles',     abbrev: '2Ch',  testament: 'OT' },
  { id: 15, name: 'Ezra',             abbrev: 'Ezr',  testament: 'OT' },
  { id: 16, name: 'Nehemiah',         abbrev: 'Neh',  testament: 'OT' },
  { id: 17, name: 'Esther',           abbrev: 'Est',  testament: 'OT' },
  { id: 18, name: 'Job',              abbrev: 'Job',  testament: 'OT' },
  { id: 19, name: 'Psalms',           abbrev: 'Psa',  testament: 'OT' },
  { id: 20, name: 'Proverbs',         abbrev: 'Pro',  testament: 'OT' },
  { id: 21, name: 'Ecclesiastes',     abbrev: 'Ecc',  testament: 'OT' },
  { id: 22, name: 'Song of Solomon',  abbrev: 'Son',  testament: 'OT' },
  { id: 23, name: 'Isaiah',           abbrev: 'Isa',  testament: 'OT' },
  { id: 24, name: 'Jeremiah',         abbrev: 'Jer',  testament: 'OT' },
  { id: 25, name: 'Lamentations',     abbrev: 'Lam',  testament: 'OT' },
  { id: 26, name: 'Ezekiel',          abbrev: 'Eze',  testament: 'OT' },
  { id: 27, name: 'Daniel',           abbrev: 'Dan',  testament: 'OT' },
  { id: 28, name: 'Hosea',            abbrev: 'Hos',  testament: 'OT' },
  { id: 29, name: 'Joel',             abbrev: 'Joe',  testament: 'OT' },
  { id: 30, name: 'Amos',             abbrev: 'Amo',  testament: 'OT' },
  { id: 31, name: 'Obadiah',          abbrev: 'Oba',  testament: 'OT' },
  { id: 32, name: 'Jonah',           abbrev: 'Jon',  testament: 'OT' },
  { id: 33, name: 'Micah',            abbrev: 'Mic',  testament: 'OT' },
  { id: 34, name: 'Nahum',            abbrev: 'Nah',  testament: 'OT' },
  { id: 35, name: 'Habakkuk',         abbrev: 'Hab',  testament: 'OT' },
  { id: 36, name: 'Zephaniah',        abbrev: 'Zep',  testament: 'OT' },
  { id: 37, name: 'Haggai',           abbrev: 'Hag',  testament: 'OT' },
  { id: 38, name: 'Zechariah',        abbrev: 'Zec',  testament: 'OT' },
  { id: 39, name: 'Malachi',          abbrev: 'Mal',  testament: 'OT' },
  { id: 40, name: 'Matthew',          abbrev: 'Mat',  testament: 'NT' },
  { id: 41, name: 'Mark',             abbrev: 'Mar',  testament: 'NT' },
  { id: 42, name: 'Luke',             abbrev: 'Luk',  testament: 'NT' },
  { id: 43, name: 'John',             abbrev: 'Joh',  testament: 'NT' },
  { id: 44, name: 'Acts',             abbrev: 'Act',  testament: 'NT' },
  { id: 45, name: 'Romans',           abbrev: 'Rom',  testament: 'NT' },
  { id: 46, name: '1 Corinthians',    abbrev: '1Co',  testament: 'NT' },
  { id: 47, name: '2 Corinthians',    abbrev: '2Co',  testament: 'NT' },
  { id: 48, name: 'Galatians',        abbrev: 'Gal',  testament: 'NT' },
  { id: 49, name: 'Ephesians',        abbrev: 'Eph',  testament: 'NT' },
  { id: 50, name: 'Philippians',      abbrev: 'Phi',  testament: 'NT' },
  { id: 51, name: 'Colossians',       abbrev: 'Col',  testament: 'NT' },
  { id: 52, name: '1 Thessalonians',  abbrev: '1Th',  testament: 'NT' },
  { id: 53, name: '2 Thessalonians',  abbrev: '2Th',  testament: 'NT' },
  { id: 54, name: '1 Timothy',        abbrev: '1Ti',  testament: 'NT' },
  { id: 55, name: '2 Timothy',        abbrev: '2Ti',  testament: 'NT' },
  { id: 56, name: 'Titus',            abbrev: 'Tit',  testament: 'NT' },
  { id: 57, name: 'Philemon',         abbrev: 'Phm',  testament: 'NT' },
  { id: 58, name: 'Hebrews',          abbrev: 'Heb',  testament: 'NT' },
  { id: 59, name: 'James',            abbrev: 'Jam',  testament: 'NT' },
  { id: 60, name: '1 Peter',          abbrev: '1Pe',  testament: 'NT' },
  { id: 61, name: '2 Peter',          abbrev: '2Pe',  testament: 'NT' },
  { id: 62, name: '1 John',           abbrev: '1Jo',  testament: 'NT' },
  { id: 63, name: '2 John',           abbrev: '2Jo',  testament: 'NT' },
  { id: 64, name: '3 John',           abbrev: '3Jo',  testament: 'NT' },
  { id: 65, name: 'Jude',             abbrev: 'Jud',  testament: 'NT' },
  { id: 66, name: 'Revelation',       abbrev: 'Rev',  testament: 'NT' },
];

export const OT_BOOKS = BOOKS.filter(b => b.testament === 'OT');
export const NT_BOOKS = BOOKS.filter(b => b.testament === 'NT');
